### ISSUE TITLE
console logging user info

### ISSUE THREAD

**Issue by SreehariJayaraj** [aromalsanthosh/picspot_frontend#1]
![image](https://user-images.githubusercontent.com/66205494/152727189-3d1d051a-7db2-4237-bd95-6d939f0835c0.png)

Was going through the app saw this I believe you forgot to remove the console.log.

**Comment by aromalsanthosh** [comment]
@sreehari2003 
Thanks for reporting, Was busy with some other work, I just saw it and fixed
